language:  generic

matrix:
    include:
        - os:   Linux
          dist: wily
          env:  SWIFT_SNAPSHOT_NAME=DEVELOPMENT-SNAPSHOT-2016-05-09-a
          sudo: required
        - os:   osx
          osx_image: xcode7.3
          env:  SWIFT_SNAPSHOT_NAME=DEVELOPMENT-SNAPSHOT-2016-05-09-a

install:
    - ./.travis/install.sh

script:
    - export SWIFTENV_ROOT="$HOME/.swiftenv"
    - export PATH="${SWIFTENV_ROOT}/bin:${SWIFTENV_ROOT}/shims:$PATH"
    - env|sort
    - make
