os:
- linux
- osx

language:  generic

sudo:      required

dist:      trusty
osx_image: xcode7.3

matrix:
    include:
        - os:  Linux
          env: SWIFT_SNAPSHOT_NAME=DEVELOPMENT-SNAPSHOT-2016-05-09-a

install:
    - ./.travis/install.sh

script:
    - env|sort
#    - export SWIFTENV_ROOT="$HOME/.swiftenv"
#    - export PATH="${SWIFTENV_ROOT}/bin:${SWIFTENV_ROOT}/shims:$PATH"
#    - export OS="`lsb_release -si | tr A-Z a-z`"
#    - export VER="`lsb_release -sr`"
    - make # SWIFT_SNAPSHOT=swift-${SWIFT_SNAPSHOT_NAME}-${OS}${VER}
