os:
- linux
- osx

language:  generic

sudo:      required

dist:      trusty
osx_image: xcode7.3

matrix:
    include:
        - os:  Linux
          env: SWIFT_SNAPSHOT_NAME=DEVELOPMENT-SNAPSHOT-2016-05-09-a

install:
    - ./.travis/install.sh
script: make

